name: Size Limit

on:
   pull_request:
   push:
      branches: main

permissions:
   contents: read

jobs:
   build:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [20.x]
      steps:
         - name: Checkout code
           uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

         - name: Setup pnpm
           uses: pnpm/action-setup@v4
           with:
              version: 9.12.2

         - name: Setup Node.js
           uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
           with:
              node-version: ${{ matrix.node-version }}
              cache: "pnpm"

         - name: Install dependencies and run size limit check
           run: |
              pnpm install --frozen-lockfile
              pnpm lint:size
